#-----Ou1st03.jl----
export mycopy_mat,
       init_snapshots_v,
       init_snapshots_t,
       get_Flag_vf_zero,
       init_PML_Por,
       init_memory_variables_Por,
       ApplyBCRight_stress1D_Por01!,
       PML_save_vel_Top_Por!,
       PML_save_vel_Bottom_Por!,
       PML_save_vel_Right_Por!,
       update_velocity_1st_Por!,
       PML_update_velocity_1st_Top_Por!,
       PML_update_velocity_1st_Bottom_Por!,
       PML_update_velocity_1st_Right_Por!,
       PML_update_velocity_1st_TopRight_Por!,
       PML_update_velocity_1st_BottomRight_Por!,
       ApplyBCRight_velocity1D_Por01!,
       ApplyBCLeft_velocity_1st_Por!,
       ApplyBCLeft_velocity_1st_atPML_Top_Por!,
       ApplyBCLeft_velocity_1st_atPML_Bottom_Por!,
       update_vr_vfr_1st_vertical,
       PML_update_memRS_1st_Top_Por!,
       PML_update_memRS_1st_Bottom_Por!,
       PML_update_memRS_1st_Right_Por!,
       PML_update_memRS_1st_TopRight_Por!,
       PML_update_memRS_1st_BottomRight_Por!,
       PML_save_stress_Top_Por!,
       PML_save_stress_Bottom_Por!,
       PML_save_stress_Right_Por!,
       update_stress_1st_Por!,
       PML_update_stress_1st_Top_Por!,
       PML_update_stress_1st_Bottom_Por!,
       PML_update_stress_1st_Right_Por!,
       PML_update_stress_1st_TopRight_Por!,
       PML_update_stress_1st_BottomRight_Por!,
       ApplyBCRight_stress1D_Por01!,
       ApplyBCLeft_stress_1st_Por!,
       ApplyBCLeft_stress_1st_atPML_Top_Por!,
       ApplyBCLeft_stress_1st_atPML_Bottom_Por!,
       ApplyBC_stress_AcousticMedia_TEST!,
       ApplyBC_stress_ElasticMedia_Ou!,
       PML_update_memPQ_1st_Top_Por!,
       PML_update_memPQ_1st_Bottom_Por!,
       PML_update_memPQ_1st_Right_Por!,
       PML_update_memPQ_1st_TopRight_Por!,
       PML_update_memPQ_1st_BottomRight_Por!,
       getRecData_from_index!,
       get_snapshots!,
       get_snapshots_t!,
       check_stability01,
       init_fields_Por,
       init_receiver,
       myricker2,
       init_PML_profile,
       init_snap




include("./PCylFDMod_Ou1st03.jl") #main modules. With acoustic, not good, but ok.
#include("./FD/Peng06Mod.jl") #Peng's exact solution to B.C.s of plane wave (MOD version. Use this.)
